select nombre from tienda.producto;
select nombre, precio from tienda.producto;
select * from tienda.producto;
select nombre, precio as 'Precio en Euro', precio*1.05 as 'Precio en Dolar' from tienda.producto;
select nombre, precio as 'euros', precio*1.05 as 'dolares' from tienda.producto;
select upper(nombre), precio from tienda.producto;
select lower(nombre), precio from tienda.producto;
select nombre, substring(upper(nombre), 0, 1) as 'Extract of name' from tienda.fabricante;
select nombre, format(precio, 2) from tienda.producto;
select nombre, format(precio, 0) from tienda.producto;
select codigo_fabricante from tienda.producto;
select distinct codigo_fabricante from tienda.producto;
select nombre from tienda.fabricante order by nombre asc;
select nombre from tienda.fabricante order by nombre desc;
select nombre from tienda.producto order by nombre asc, precio desc;
select * from tienda.fabricante limit 5;
select * from tienda.fabricante limit 3, 2;
select nombre, precio from tienda.producto order by precio limit 1;
select nombre, precio from tienda.producto order by precio desc limit 1;
select nombre, codigo_fabricante from tienda.producto where codigo_fabricante=2;
select p.nombre, p.precio, f.nombre from tienda.producto p join tienda.fabricante f where p.codigo_fabricante = f.codigo;
select p.nombre, p.precio, f.nombre from tienda.producto p join tienda.fabricante f where p.codigo_fabricante = f.codigo order by f.nombre asc;
select p.nombre, p.precio, p.codigo_fabricante, f.nombre from tienda.producto p join tienda.fabricante f where p.codigo_fabricante = f.codigo;
select p.nombre, p.precio, f.nombre from tienda.producto p join tienda.fabricante f where p.codigo_fabricante = f.codigo order by precio limit 1;
select p.nombre, p.precio, f.nombre from tienda.producto p join tienda.fabricante f where p.codigo_fabricante = f.codigo order by precio desc limit 1;
select p.nombre from tienda.producto p join tienda.fabricante f where p.codigo_fabricante = f.codigo and f.nombre = 'lenovo';
